Jared/readme sub module
Esri/arcgis-runtime-samples-qt pull request #1135
Opened 2020-11-02 22:46 UTC by jared-2016

@ldanzinger Ready for review. Thank you!

Let me know what you think on these changes referencing the toolkit.

2020-11-02 22:52 UTC, ldanzinger requested changes

2020-11-02 22:52 UTC, ldanzinger commented on README.md
>  * Qt SDK 5.15 or higher (Open source or commercial)
Just noticed - this should be 5.15.1

2020-11-02 22:52 UTC, ldanzinger commented on README.md
> +* [ArcGIS Runtime Toolkit - Qt](https://github.com/Esri/arcgis-runtime-toolkit-qt) is required as some samples utilize toolkit components. For more information on the toolkit please visit, [Building
i'd leave out the blog link - that's more of a background detail that isn't required for basic setup instructions of the sample repo

```suggestion
* [ArcGIS Runtime Toolkit - Qt](https://github.com/Esri/arcgis-runtime-toolkit-qt) is required as some samples utilize toolkit components. 
```

2020-11-02 22:52 UTC, ldanzinger commented on README.md
> +* Note - if you want to contribute to the toolkit repository as well, you will need to follow the fork step, [Fork the repo](#fork-the-repo), from above but for the toolkit instead.
> [Fork the repo](#fork-the-repo), from above but for the toolkit instead.

I get what you mean, but this is a bit clunky. I'd maybe just leave this detail out - most people won't want to contribute back to the project. The toolkit repo has instructions on how to do it, so I think we can leave it out from here.

2020-11-02 22:57 UTC, jared-2016 commented on README.md
>  * Qt SDK 5.15 or higher (Open source or commercial)
fixed

2020-11-02 22:58 UTC, jared-2016 commented
Should be good to go.

2020-11-02 22:58 UTC, ldanzinger approved these changes
LGTM

2020-11-03 14:19 UTC, merged

2020-11-03 14:19 UTC, jared-2016 commented
updates samples readme to give instructions on the proper location for the toolkit as it's needed for individual samples.