Andrewbladon/add service geodatabase to un samples
Esri/arcgis-runtime-samples-qt pull request #1297
Opened 2021-09-03 07:31 UTC by AndrewBladon

2021-09-06 16:57 UTC, lsmallwood approved these changes
looks pretty good to me @AndrewBladon. A few comments but no need to re-review.

2021-09-06 16:57 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_CppSamples/UtilityNetwork/DisplayUtilityAssociations/DisplayUtilityAssociations.cpp
> +#include "UtilityNetworkListModel.h"
this list should be alphabetized

2021-09-06 16:57 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_CppSamples/UtilityNetwork/DisplayUtilityAssociations/README.md
> +1. Create an `UtilityNetwork` with a feature service URL, add it to the map's `utilityNetworks` array, then load it.
for qt we'd call it a list or listModel rather than an array

2021-09-06 16:57 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_CppSamples/UtilityNetwork/PerformValveIsolationTrace/PerformValveIsolationTrace.cpp
> +  m_graphicParent(new QObject()),
existing code but i'm curious why this doesn't get a parent

2021-09-06 16:57 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_CppSamples/UtilityNetwork/PerformValveIsolationTrace/README.md
> +2. Create and load an `ServiceGeodatabase` with a feature service URL and get tables with their layer IDs.
```suggestion
2. Create and load a `ServiceGeodatabase` with a feature service URL and get tables with their layer IDs.
```

2021-09-06 16:57 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_CppSamples/UtilityNetwork/TraceUtilityNetwork/TraceUtilityNetwork.cpp
> +  m_deviceFeatureTable = m_serviceGeodatabase->table(0);
this looks like it should handle a failure to load `m_serviceGeodatabase`

2021-09-06 16:57 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_CppSamples/UtilityNetwork/TraceUtilityNetwork/TraceUtilityNetwork.cpp
> +  m_lineFeatureTable = m_serviceGeodatabase->table(3);
this could probably do with a comment to say what `3` is (e.g. your choosing the 3rd table)

2021-09-06 16:57 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_CppSamples/UtilityNetwork/TraceUtilityNetwork/TraceUtilityNetwork.cpp
> +  m_busy = true;
minor thing - but you could extract `setBusy` as a function that takes care of setting the variable and emitting the signal

2021-09-06 16:57 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_QMLSamples/UtilityNetwork/DisplayUtilityAssociations/README.md
> +1. Create an `UtilityNetwork` with a feature service URL, add it to the map's `utilityNetworks` array, then load it.
list rather than array

2021-09-06 16:57 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_QMLSamples/UtilityNetwork/PerformValveIsolationTrace/README.md
> +2. Create and load an `ServiceGeodatabase` with a feature service URL and get tables by their layer IDs.
```suggestion
2. Create and load a `ServiceGeodatabase` with a feature service URL and get tables by their layer IDs.
```

2021-09-06 16:57 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_QMLSamples/UtilityNetwork/TraceUtilityNetwork/TraceUtilityNetwork.qml
> +            username: "viewer01"
surprised we bake these in

2021-09-07 16:02 UTC, Gela reviewed
Just a few small suggestions

2021-09-07 16:02 UTC, Gela commented on ArcGISRuntimeSDKQt_CppSamples/UtilityNetwork/TraceUtilityNetwork/TraceUtilityNetwork.cpp
> +  if (hasErrorOccurred(error))
Same comment here about brackets

2021-09-07 16:02 UTC, Gela commented on ArcGISRuntimeSDKQt_CppSamples/UtilityNetwork/TraceUtilityNetwork/TraceUtilityNetwork.cpp
> +  return;
Same comment here about brackets

2021-09-07 16:02 UTC, Gela commented on ArcGISRuntimeSDKQt_QMLSamples/UtilityNetwork/DisplayUtilityAssociations/README.md
> +1. Create an `UtilityNetwork` with a feature service URL, add it to the map's `utilityNetworks` list, then load it.
I think this should say "a `UtilityNetwork`"

2021-09-07 18:04 UTC, tanneryould requested changes
Looks good to me, just a few stylistic suggestions and grammatical errors to resolve.

2021-09-07 18:04 UTC, tanneryould commented on ArcGISRuntimeSDKQt_CppSamples/UtilityNetwork/TraceUtilityNetwork/TraceUtilityNetwork.cpp
> +  emit busyChanged();
```suggestion
  m_busy = status;
  emit busyChanged();
```

2021-09-07 18:04 UTC, tanneryould commented on ArcGISRuntimeSDKQt_QMLSamples/UtilityNetwork/TraceUtilityNetwork/TraceUtilityNetwork.qml
> +
If no properties follow the component declaration then it doesn't need a new line before the next component is declared.
```suggestion
```

2021-09-08 19:27 UTC, tanneryould approved these changes
LGTM

2021-09-13 08:27 UTC, merged