Add Display Dimensions sample
Esri/arcgis-runtime-samples-qt pull request #1333
Opened 2021-12-08 18:44 UTC by AndrewBladon

2021-12-13 19:20 UTC, Gela approved these changes

2021-12-14 19:32 UTC, tanneryould requested changes
Couple of changes needed, especially the offline data paths

2021-12-14 19:32 UTC, tanneryould commented on ArcGISRuntimeSDKQt_CppSamples/Layers/DisplayDimensions/DisplayDimensions.cpp
> +      setDimensionLayerName(m_dimensionLayer->name());
Will there be just one dimension layer and can we `break` out of the `for` loop after finding it?

2021-12-14 19:32 UTC, tanneryould commented on ArcGISRuntimeSDKQt_CppSamples/Layers/DisplayDimensions/README.metadata.json
> +    "description": "Display dimension features from a mobile map package.",
```suggestion
    "category": "Layers",
    "dataItems": [
        {
            "itemId": "f5ff6f5556a945bca87ca513b8729a1e",
            "path": "~/ArcGIS/Runtime/Data/mmpk/Edinburgh_Pylon_Dimensions.mmpk"
        }
    ],
    "description": "Display dimension features from a mobile map package.",
```

2021-12-14 19:32 UTC, tanneryould commented on ArcGISRuntimeSDKQt_QMLSamples/Layers/DisplayDimensions/README.metadata.json
> +    "description": "Display dimension features from a mobile map package.",
```suggestion
    "category": "Layers",
    "dataItems": [
        {
            "itemId": "f5ff6f5556a945bca87ca513b8729a1e",
            "path": "~/ArcGIS/Runtime/Data/mmpk/Edinburgh_Pylon_Dimensions.mmpk"
        }
    ],
    "description": "Display dimension features from a mobile map package.",
```

2021-12-14 19:32 UTC, tanneryould commented on ArcGISRuntimeSDKQt_QMLSamples/Layers/DisplayDimensions/DisplayDimensions.qml
> +import Esri.ArcGISRuntime 100.13
We'll need to update these to 100.14 soon, and they're not in Marton's PR

2021-12-14 19:32 UTC, tanneryould commented on ArcGISRuntimeSDKQt_QMLSamples/Layers/DisplayDimensions/DisplayDimensions.qml
> +    property int indexOfDimensionLayer: 0
Any reason for the extra line here?
```suggestion
    readonly property url dataPath: System.userHomePath + "/ArcGIS/Runtime/Data/mmpk/"
    property string errorMessage: ""
    property int indexOfDimensionLayer: 0
```

2021-12-14 19:32 UTC, tanneryould commented on ArcGISRuntimeSDKQt_QMLSamples/Layers/DisplayDimensions/DisplayDimensions.qml
> +            var viewpointCenter = ArcGISRuntimeEnvironment.createObject("ViewpointCenter", {center: viewpointPoint, targetScale: 30000});
Can these be `const`? If not, `let`?

2021-12-15 17:57 UTC, tanneryould approved these changes
LGTM, thanks!

2021-12-16 09:21 UTC, lsmallwood requested changes
looks cool @AndrewBladon 👍  A few comments to look at.

2021-12-16 09:21 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_CppSamples/Layers/DisplayDimensions/DisplayDimensions.cpp
> +  // If no error's have occurred, the mmpk is loaded, and there is only one map in the mmpk, the map in the mmpk can be
```suggestion
  // If no errors have occurred, the mmpk is loaded, and there is only one map in the mmpk, the map in the mmpk can be
```

2021-12-16 09:21 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_CppSamples/Layers/DisplayDimensions/DisplayDimensions.cpp
> +    m_mapView->setMap(m_map);
there is a theoretical chance that `m_map` hasn't been set when this is called. probably will never happen but may be worth a check

2021-12-16 09:21 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_CppSamples/Layers/DisplayDimensions/DisplayDimensions.cpp
> +    m_map->setInitialViewpoint(Viewpoint(Point(-3.3098678, 55.9074044, SpatialReference::wgs84()), 30000));
i don't think you should need to do this: the mmpk can encode a starting location if you want one for the sample...

2021-12-16 09:21 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_CppSamples/Layers/DisplayDimensions/DisplayDimensions.cpp
> +    setCheckBoxesEnabled(false);
nit-pick: personally i think that the cpp shouldn't work in terms of ui elements such as check-boxes which are a view concern really. could this be called `setDimensionsAvailable` or something?

2021-12-16 09:21 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_CppSamples/Layers/DisplayDimensions/DisplayDimensions.cpp
> +      m_dimensionLayer = dynamic_cast<DimensionLayer*>(layer);
after doing a type check on the enum you may as well do a `static_cast`... there's really no point in doing the dynamic cast unless you then check the returned type

2021-12-16 09:21 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_CppSamples/Layers/DisplayDimensions/DisplayDimensions.cpp
> +  m_mapView->setMap(m_map);
good chance `m_map` hasn't been set by the time this is called since we need to load it from the mmpk

2021-12-16 09:21 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_CppSamples/Layers/DisplayDimensions/DisplayDimensions.cpp
> +void DisplayDimensions::setCheckBoxesEnabled(const bool& status)
don't pass primitive types by const ref

2021-12-16 09:21 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_CppSamples/Layers/DisplayDimensions/DisplayDimensions.h
> +  Q_PROPERTY(bool checkBoxesEnabled READ checkBoxesEnabled NOTIFY checkBoxesEnabledChanged)
rename this property i think

2021-12-16 09:21 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_CppSamples/Layers/DisplayDimensions/README.md
> +This sample shows a subset of the network of pylons, substations, and power lines around Edinburgh, Scotland within a [Edinburgh Pylon Dimensions mobile map package](https://arcgis.com/home/item.html
```suggestion
This sample shows a subset of the network of pylons, substations, and power lines around Edinburgh, Scotland within an [Edinburgh Pylon Dimensions mobile map package](https://arcgis.com/home/item.html?id=f5ff6f5556a945bca87ca513b8729a1e). The data was digitised from satellite imagery and is intended to be used for illustrative purposes only.
```

2021-12-16 09:21 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_QMLSamples/Layers/DisplayDimensions/DisplayDimensions.qml
> +                        if (definitionExpressionToggle.checkState == Qt.Checked) {
```suggestion
                        if (definitionExpressionToggle.checkState === Qt.Checked) {
```

2021-12-16 09:21 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_QMLSamples/Layers/DisplayDimensions/DisplayDimensions.qml
> +                    toggleBoxTitle.text = mmpk.maps[0].operationalLayers.get(counter).name;
you need to add a `break` here so you don't keep searching after you find the layer you are looking for

2021-12-16 16:52 UTC, lsmallwood approved these changes
LGTM 👍

2021-12-16 16:52 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_CppSamples/Layers/DisplayDimensions/DisplayDimensions.cpp
> +    // Check to ensure that m_map has been initialised properly.
```suggestion
    // Check to ensure that m_mapView has been initialised properly.
```

2021-12-16 16:56 UTC, merged