Release/100.13.0
Esri/arcgis-runtime-samples-qt pull request #1337
Opened 2021-12-15 20:43 UTC by tanneryould

Merges changes from 100.13 into `main`. 

Note: I scrolled through each file to verify changes.

2021-12-15 20:50 UTC, tanneryould commented
metadata checker raising false flags

2021-12-15 21:11 UTC, ldanzinger approved these changes
Since you already have reviewed each file, I did a spot check and everything looks good.

2021-12-15 21:22 UTC, Gela approved these changes
Randomly reviewed a handful of files and they looked good. Here's to hoping the other 900 are okay too (Chrome keeps crashing on me due to the size of this PR!)

2021-12-16 20:52 UTC, MicahSamaduroff requested changes

2021-12-16 20:52 UTC, MicahSamaduroff commented on ArcGISRuntimeSDKQt_CppSamples/Maps/ChangeBasemap/main.cpp
> +void setAPIKey(const QGuiApplication& app, QString apiKey)
This method already exists, and this causes a compiler error when trying to build the sample

2021-12-17 18:33 UTC, MicahSamaduroff approved these changes
👍 Looks good to me, I just reviewed that one change and not the whole PR.

2021-12-17 18:40 UTC, merged