Update jobStatusChanged signal to statusChanged
Esri/arcgis-runtime-samples-qt pull request #1383
Opened 2022-04-26 21:57 UTC by Gela

Update deprecated "jobStatusChanged" signal to statusChanged.

```issue: common-samples/3494```

2022-04-27 00:28 UTC, tanneryould requested changes
`statusChanged` provides access to the `JobStatus` class which we should use in lieu of `job->jobStatus()` . See [Generate offline map](https://github.com/Esri/arcgis-runtime-samples-qt/blob/v.next/ArcGISRuntimeSDKQt_CppSamples/Maps/GenerateOfflineMap/GenerateOfflineMap.cpp#L108) for an example.

2022-05-04 03:26 UTC, Gela commented
@lsmallwood could you take a look and verify it's good to be merged?

2022-05-04 08:50 UTC, lsmallwood approved these changes
Looks good @Gela. I think we can avoid polling the job again for the status in the qml samples but otherwise looks good.

Did we have any connections for `messagesChanged`? That can be replaced as well if so.

2022-05-04 08:50 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_QMLSamples/Maps/ApplyScheduledMapUpdates/ApplyScheduledMapUpdates.qml
> +                syncJob.statusChanged.connect(()=> {
i think you should be able to get the status as an arg to this connection, rather than having to poll the `syncJob` again

2022-05-04 08:50 UTC, lsmallwood commented on ArcGISRuntimeSDKQt_QMLSamples/Maps/DownloadPreplannedMap/DownloadPreplannedMap.qml
> +                    job.statusChanged.connect(()=> {
same here - can you get the status as an arg to the connection?

2022-05-06 17:13 UTC, tanneryould approved these changes

2022-05-10 23:30 UTC, merged