New Sample: Navigate a route with rerouting
Esri/arcgis-runtime-samples-qt pull request #1445
Opened 2022-08-09 05:40 UTC by Gela

# Description

Add a sample for navigating a route with rerouting.

## Type of change

- [ ] Bug fix
- [x] New sample implementation
- [ ] Sample viewer enhancement
- [ ] Other enhancement

**Platforms tested on**:

- [x] Windows
- [x] Android
- [ ] Linux
- [ ] macOS
- [ ] iOS

## Checklist

- [ ] Runs and compiles on all active platforms
- [x] Branch is up to date with the latest main/v.next
- [x] All merge conflicts have been resolved
- [ ] Self-review of changes
- [x] There are no warnings related to changes
- [x] No unrelated changes have been made to any other code or project files
- [x] Code is commented with correct formatting (CTRL+i)
- [] All variable and method names are camel case
- [ ] There is no leftover commented code
- [x] Screenshots are correct size and display in description tab (500px by 500px, platform agnostic)
- [x] If adding a new sample, it is added to the sample viewer
- [ ] Cherry-picked to Main branch (if applicable)

2022-08-09 20:03 UTC, tanneryould requested changes
Unfortunately on Mac the C++ implementation shows the wrong text directions, and the QML implementation does not reroute.

2022-08-15 23:57 UTC, shubham7109 commented on ArcGISRuntimeSDKQt_CppSamples/Routing/NavigateARouteWithRerouting/NavigateARouteWithRerouting.cpp
> +        m_directionManeuvers = m_route.directionManeuvers(this)->directionManeuvers();
Add these lines only when RouteTracker returns `rerouteCompleted`

2022-08-15 23:59 UTC, shubham7109 commented on ArcGISRuntimeSDKQt_CppSamples/Routing/NavigateARouteWithRerouting/NavigateARouteWithRerouting.cpp
> +        m_directionManeuvers = m_route.directionManeuvers(this)->directionManeuvers();
Maybe try adding it somewhere in [this](https://github.com/Esri/arcgis-runtime-samples-qt/blob/6e5fe638d9f0b810f45273e6ca96a7c3a25cd6a7/ArcGISRuntimeSDKQt_CppSamples/Routing/NavigateARouteWithRerouting/NavigateARouteWithRerouting.cpp#L253) method.

2022-08-23 18:38 UTC, tanneryould requested changes
Quick thing to add to the metadata because this requires the offline geodatabase

2022-08-23 18:38 UTC, tanneryould commented on ArcGISRuntimeSDKQt_CppSamples/Routing/NavigateARouteWithRerouting/README.metadata.json
> +    "description": "Navigate between two points and dynamically recalculate an alternate route when the original route is unavailable.",
This will need the offline data items as I put in the QML implementation

2022-08-23 18:38 UTC, tanneryould commented on ArcGISRuntimeSDKQt_CppSamples/Routing/NavigateARouteWithRerouting/README.md
> +## About the data
Needs offline data as well

2022-08-23 18:38 UTC, tanneryould commented on ArcGISRuntimeSDKQt_CppSamples/Routing/NavigateARouteWithRerouting/README.md
> +
```suggestion

## Offline data

The data used by this sample is available on [ArcGIS Online](https://arcgisruntime.maps.arcgis.com/home/item.html?id=df193653ed39449195af0c9725701dca).

Link | Local Location
---------|-------|
|[San Diego Streets TPKX](https://arcgisruntime.maps.arcgis.com/home/item.html?id=df193653ed39449195af0c9725701dca)| `<userhome>`/ArcGIS/Runtime/Data/tpkx/san_diego |

```

2022-08-23 18:38 UTC, tanneryould commented on ArcGISRuntimeSDKQt_CppSamples/Routing/NavigateARouteWithRerouting/README.metadata.json
> +    "description": "Navigate between two points and dynamically recalculate an alternate route when the original route is unavailable.",
```suggestion
    "category": "Routing",
    "dataItems": [
        {
            "itemId": "df193653ed39449195af0c9725701dca",
            "path": "~/ArcGIS/Runtime/Data/tpkx/san_diego/san_diego_offline_routing.zip"
        }
    ],
    "description": "Navigate between two points and dynamically recalculate an alternate route when the original route is unavailable.",
```

2022-08-23 18:59 UTC, tanneryould requested changes
Couple other changes as well

2022-08-23 18:59 UTC, tanneryould commented on ArcGISRuntimeSDKQt_CppSamples/Routing/NavigateARouteWithRerouting/NavigateARouteWithRerouting.cpp
> +        m_simulatedLocationDataSource->stop();
Reenable the navigation button when the destination is reached
```suggestion
        m_simulatedLocationDataSource->stop();
        m_navigationEnabled = true;
        emit navigationEnabledChanged();
```

2022-08-23 18:59 UTC, tanneryould commented on ArcGISRuntimeSDKQt_CppSamples/Routing/NavigateARouteWithRerouting/NavigateARouteWithRerouting.cpp
> +const Point aerospaceMuseumPoint(-117.147230, 32.730467, SpatialReference::wgs84());
set these to the first and last points of the tourPolylineJson so the navigation properly ends
```suggestion
const Point conventionCenterPoint(-117.160386727066026, 32.706608204740171, SpatialReference::wgs84());
const Point aerospaceMuseumPoint(-117.146679999797271, 32.730351428946854, SpatialReference::wgs84());
```

2022-08-23 18:59 UTC, tanneryould commented on ArcGISRuntimeSDKQt_CppSamples/Routing/NavigateARouteWithRerouting/NavigateARouteWithRerouting.qml
> +                    anchors.margins: 20
This is a relic from the old sample but we should list the anchors after the id
```suggestion
                    id: backBox
                    anchors {
                        top: parent.top
                        left: parent.left
                        margins: 20
                    }
                    z: 1
                    width: buttonRow.width * 1.5
                    height: 200
                    color: "#FBFBFB"
                    border.color: "black"
```

2022-08-23 19:57 UTC, tanneryould approved these changes
LGTM, runs on Mac!

2022-08-23 21:52 UTC, merged