Clip geometry and cut geometry reset button
Esri/arcgis-runtime-samples-qt pull request #1449
Opened 2022-08-19 19:38 UTC by Gela

# Description

Add a reset button to the samples "Cut Geometry" and "Clip Geometry" to bring them back to their initial/opening stage. Screenshots did not need to be updated since the original ones did not include any buttons either.

## Type of change

- [x] Bug fix
- [ ] New sample implementation
- [ ] Sample viewer enhancement
- [ ] Other enhancement

**Platforms tested on**:

- [x] Windows
- [ ] Android
- [ ] Linux
- [ ] macOS
- [ ] iOS

2022-08-22 20:56 UTC, tanneryould reviewed
The C++ implementation of "Cut geometry" gets stuck in a soft-locked state so that needs to be fixed, and the rest of the comments are just strong suggestions, but not required. 

Alternatively to two buttons you could have the one button change text after each click and have each text correspond to different functions.

2022-08-22 20:56 UTC, tanneryould commented on ArcGISRuntimeSDKQt_CppSamples/Geometry/CutGeometry/CutGeometry.qml
> +            enabled = false;
This should be disabled by default, enabled when the cut button is clicked, and enable the cut button when this is clicked. 
```suggestion
        enabled: false
        onClicked: {
            resetPolygon();
            enabled = false;
            cutButton.enabled = true;
            // insert resetButton.enabled = true; at line 50 or so
```
Currently the cut button is disabled after it's clicked and the reset button is disabled after it's clicked, leaving the app in a soft-locked state.

![Screen Shot 2022-08-22 at 1 51 09 PM](https://user-images.githubusercontent.com/48941951/186016472-7c196e8a-c1c1-4987-b719-046d6cef31b2.png)

2022-08-22 20:56 UTC, tanneryould commented on ArcGISRuntimeSDKQt_CppSamples/Geometry/ClipGeometry/ClipGeometry.qml
> +        id: resetButton
Consider having this button disabled by default, enabled once clipButton is clicked, then disabled again when resetButton itself is clicked

2022-08-22 20:56 UTC, tanneryould commented on ArcGISRuntimeSDKQt_QMLSamples/Geometry/ClipGeometry/ClipGeometry.qml
> +        id: resetButton
Same comment as C++

2022-08-22 20:56 UTC, tanneryould commented on ArcGISRuntimeSDKQt_QMLSamples/Geometry/CutGeometry/CutGeometry.qml
> +    function resetPolygon() {
Consider making this disabled by default, enabled after clicking cut, and then disabled again when clicked.

2022-08-22 20:57 UTC, tanneryould requested changes
Woops, I meant to mark "Request changes"

2022-08-24 05:43 UTC, Gela commented
Thanks @tanneryould, I like the 1 button for clip/cut/reset better so I made the changes to do that instead. Please take another look.

2022-08-24 17:57 UTC, tanneryould approved these changes
Small change to avoid JS type coercion, but no need for re-review

2022-08-24 17:57 UTC, tanneryould commented on ArcGISRuntimeSDKQt_CppSamples/Geometry/ClipGeometry/ClipGeometry.qml
> +            if (clipOrResetButton.text == "Clip")
```suggestion
            if (clipOrResetButton.text === "Clip")
```

2022-08-24 17:57 UTC, tanneryould commented on ArcGISRuntimeSDKQt_CppSamples/Geometry/CutGeometry/CutGeometry.qml
> +            if (cutOrResetButton.text == "Cut")
```suggestion
            if (cutOrResetButton.text === "Cut")
```

2022-08-24 17:57 UTC, tanneryould commented on ArcGISRuntimeSDKQt_QMLSamples/Geometry/ClipGeometry/ClipGeometry.qml
> +            if (clipOrResetButton.text == "Clip")
```suggestion
            if (clipOrResetButton.text === "Clip")
```

2022-08-24 17:57 UTC, tanneryould commented on ArcGISRuntimeSDKQt_QMLSamples/Geometry/CutGeometry/CutGeometry.qml
> +            if (cutOrResetButton.text == "Cut")
```suggestion
            if (cutOrResetButton.text === "Cut")
```

2022-08-24 18:01 UTC, merged